Adding more vms to test

diff --git a/blobfuse-nightly.yml b/blobfuse-nightly.yml
--- a/blobfuse-nightly.yml
+++ b/blobfuse-nightly.yml
@@ -49,6 +49,10 @@ jobs:
               imageName: 'ubuntu-20.04' 
               containerName: 'test-cnt-ubn-20'
               quickTestDir: 'ubn20'
+            Ubuntu-22:
+              imageName: 'ubuntu-22.04' 
+              containerName: 'test-cnt-ubn-22'
+              quickTestDir: 'ubn22'
 
           ${{ if eq(parameters.exhaustive_test, false) }}:
             Ubuntu-18:
@@ -866,7 +870,7 @@ jobs:
 
 
   - ${{ if eq(parameters.exhaustive_test, true) }}:
-    - job: Set_3
+    - job: Set_2
       timeoutInMinutes: 30
       strategy:
         matrix:
@@ -1132,7 +1136,7 @@ jobs:
           displayName: 'Clean Agent Directories'
           condition: always()
 
-    - job: Set_4
+    - job: Set_3
       timeoutInMinutes: 30
       strategy:
         matrix:
@@ -1293,7 +1297,7 @@ jobs:
           displayName: 'Clean Agent Directories'
           condition: always()
 
-    - job: Set_5
+    - job: Set_4
       timeoutInMinutes: 30
       strategy:
         matrix:
@@ -1459,7 +1463,7 @@ jobs:
           displayName: 'Clean Agent Directories'
           condition: always()
 
-    - job: Set_6
+    - job: Set_5
       timeoutInMinutes: 30
       strategy:
         matrix:
@@ -1619,6 +1623,216 @@ jobs:
           displayName: 'Clean Agent Directories'
           condition: always()
 
+    - job: Set_6
+      timeoutInMinutes: 30
+      strategy:
+        matrix:
+          Mariner:
+            DistroVer: "Mariner"
+            AgentName : "blobfuse-mariner"
+            Description: "CBL-Mariner Linux"
+            containerName: 'test-cnt-mari-1'
+      pool:
+        name: "blobfuse-mariner-pool"
+        demands:
+          - ImageOverride -equals $(AgentName)
+
+      variables:
+      - group: NightlyBlobFuse
+      - name: WORK_DIR
+        value: "/usr/pipeline/blobfuse"
+      - name: ROOT_DIR
+        value: "/usr/pipeline/blobfuse/azure-storage-fuse"
+      - name: skipComponentGovernanceDetection
+        value: true
+
+      - name: MOUNT_DIR
+        value: "/usr/pipeline/blob_mnt"
+      - name: TEMP_DIR
+        value: "/usr/pipeline/temp"
+      - name: BLOBFUSE_CFG_FILE
+        value: "/usr/pipeline/blobfuse/azure-storage-fuse/test/blobfuse.cfg"
+      
+      steps:
+        # DevOps checks for a specific git version and it fails on some distros
+        # so instead of pipeline checking out the code, do it manually
+        - checkout: none
+
+        # Install all dependencies
+        - script: |
+            echo $(Description)
+            hostnamectl
+          displayName: "Print Agent Info"
+
+        # Go tool installer
+        - task: GoTool@0
+          inputs:
+            version: '1.16.2'
+          displayName: "Install Go Version"
+
+        # Install all dependencies
+        - script: |
+            sudo tdnf update -y
+            sudo tdnf install git wget tar make cmake gcc gcc-c++ curl-devel gnutls-devel libuuid-devel boost-devel libgcrypt-devel rpm-build golang libarchive -y
+          displayName: "Basic Tools Setup"
+
+        - script: |
+            sudo tdnf install python3-devel -y
+            wget https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-linux-x86_64.sh -O cmake.sh
+            sudo mv cmake.sh /opt
+            sudo chmod +x /opt/cmake.sh
+            sudo sh /opt/cmake.sh --prefix=/usr/ --exclude-subdir
+          displayName: "Python3 and CMake setup"
+          condition: eq(variables['AgentName'], 'blobfuse-rhel7_5')
+
+        - script: |
+            sudo tdnf install cmake3 -y
+            sudo ln -sf /usr/bin/cmake3 /usr/bin/cmake
+          displayName: "CMake version"
+          condition: eq(variables['AgentName'], 'blobfuse-centos7')
+
+        # Install libfuse
+        - script: |
+            sudo tdnf install fuse fuse-devel -y
+          displayName: "libFuse Setup"
+
+        # Prebuild cleanup
+        - script: |
+            sudo rm -rf $(WORK_DIR)
+          displayName: "Prebuild cleanup"
+
+        # Checkout code
+        - script: |
+            sudo mkdir -p $(WORK_DIR)
+            sudo chown -R `whoami` $(WORK_DIR)
+            chmod 777 $(WORK_DIR)
+          displayName: "Create Directory structure"
+
+        # Checkout code
+        - script: |
+            git clone https://github.com/Azure/azure-storage-fuse
+          displayName: "Checkout code"
+          workingDirectory: $(WORK_DIR)
+
+        # Checkout branch
+        - script: |
+            echo $(Build.SourceBranch)
+            echo "Going for checkout of " `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`  
+            git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`   
+          displayName: "Checkout Branch"
+          workingDirectory: $(ROOT_DIR)
+
+        # List commits consumed for this build
+        - script: |
+            echo "Below commits were done in last 12 hours : " `date` 
+            git --no-pager log --since="12 hours ago" --stat
+          displayName: "List Commits"
+          workingDirectory: $(ROOT_DIR)
+
+        # Build the blobFuse binary
+        - script: |
+            sudo chmod +x build.sh
+            . ./build.sh
+          displayName: "Build BlobFuse"
+          workingDirectory: $(ROOT_DIR)
+
+        # Test the binary just to make sure it was built fine
+        - script: |
+            ./build/blobfuse --version
+          displayName: "Test the binary"
+          workingDirectory: $(ROOT_DIR)
+
+        # Add the test work here
+        # Create directory structures for the basic testing
+        - script: |
+            sudo mkdir $(MOUNT_DIR)
+            sudo chown -R `whoami` $(MOUNT_DIR)
+            chmod 777 $(MOUNT_DIR)
+            sudo mkdir $(TEMP_DIR)
+            sudo chown -R `whoami` $(TEMP_DIR)
+            chmod 777 $(TEMP_DIR)
+          displayName: "Create Directories"
+        
+        # --- Create config files for testing
+        - script: |
+            sudo touch $(BLOBFUSE_CFG_FILE)
+            sudo chown -R `whoami` $(BLOBFUSE_CFG_FILE)
+            chmod 777 $(BLOBFUSE_CFG_FILE)
+            echo "accountName " $(NIGHTLY_STO_ACC_NAME) > $(BLOBFUSE_CFG_FILE)
+            echo "accountKey " $(NIGHTLY_STO_ACC_KEY) >> $(BLOBFUSE_CFG_FILE)
+            echo "authType Key" >> $(BLOBFUSE_CFG_FILE)
+            echo "containerName " $(containerName) >> $(BLOBFUSE_CFG_FILE)
+            cat $(BLOBFUSE_CFG_FILE)
+            echo "Account : " $(NIGHTLY_STO_ACC_NAME)
+          displayName: "Create config file"
+
+        # Mount a directory for feature test (Block) and run it
+        - script:  |
+            curl --version
+            sudo fusermount -u $(MOUNT_DIR)
+            sudo rm -rf $(MOUNT_DIR)/*
+            sudo rm -rf $(TEMP_DIR)/*
+            ./build/blobfuse $(MOUNT_DIR) --tmp-path=$(TEMP_DIR) --config-file=$(BLOBFUSE_CFG_FILE) --file-cache-timeout-in-seconds=0 --use-adls=true --use-attr-cache=true
+          workingDirectory: $(ROOT_DIR)
+          displayName: "Mount Blobfuse"
+
+        - script: | 
+            sudo rm -rf $(MOUNT_DIR)/*  
+            cd test
+            go test -v feature_test.go -args -mnt-path=$(MOUNT_DIR) -adls=true
+          workingDirectory: $(ROOT_DIR)
+          displayName: TEST - ADLS FeatureTest
+          timeoutInMinutes: 20
+
+        - script:  |
+            rm -rf $(MOUNT_DIR)/*
+            sudo fusermount -u $(MOUNT_DIR)
+          workingDirectory: $(ROOT_DIR)
+          displayName: 'Unmount blobfuse'
+          timeoutInMinutes: 5
+          condition: always()
+
+        # --- Negative testing for auth failure post fork
+        - script: |
+            sudo touch $(BLOBFUSE_CFG_FILE)
+            sudo chown -R `whoami` $(BLOBFUSE_CFG_FILE)
+            chmod 777 $(BLOBFUSE_CFG_FILE)
+            echo "accountName " $(NIGHTLY_STO_ACC_NAME) > $(BLOBFUSE_CFG_FILE)
+            echo "accountKey " $(NIGHTLY_STO_ACC_KEY) "abc" >> $(BLOBFUSE_CFG_FILE)
+            echo "authType Key" >> $(BLOBFUSE_CFG_FILE)
+            echo "containerName " $(containerName) >> $(BLOBFUSE_CFG_FILE)
+            cat $(BLOBFUSE_CFG_FILE)
+            echo "Account : " $(NIGHTLY_STO_ACC_NAME)
+          displayName: "Create config file - Negative"
+          # condition: or(eq(variables.containerName, 'test-cnt-rhel-75-test'), eq(variables.containerName, 'test-cnt-rhel-82'))
+
+        # Mount a directory for feature test (Block) and run it
+        # This mount is bound to fail so to ignore the exit code of the blobfuse use '|| :' to redirect output to null
+        # with this output will come on screen but the piepline task will not fail due to exit(1) by blobfuse
+        - script:  |
+            ./build/blobfuse $(MOUNT_DIR) --tmp-path=$(TEMP_DIR) --config-file=$(BLOBFUSE_CFG_FILE) --file-cache-timeout-in-seconds=0 --use-adls=true --use-attr-cache=true 2>&1 || :
+          workingDirectory: $(ROOT_DIR)
+          displayName: "Mount Blobfuse - Negative"
+          # condition: or(eq(variables.containerName, 'test-cnt-rhel-75-test'), eq(variables.containerName, 'test-cnt-rhel-82'))
+
+        - script:  |
+            rm -rf $(MOUNT_DIR)/*
+            sudo fusermount -u $(MOUNT_DIR)
+            sudo rm -rf $(TEMP_DIR)/
+            sudo rm -rf $(MOUNT_DIR)
+            sudo rm -rf $(BLOBFUSE_CFG_FILE)
+            sudo rm -rf $(WORK_DIR)
+          workingDirectory: $(ROOT_DIR)
+          displayName: 'Cleanup Directories'
+          timeoutInMinutes: 5
+          condition: always()
+
+        - script: |
+            pwd
+            cd /`pwd | cut -d '/' -f 2,3,4,5`
+            sudo rm -rf [0-9]
+          displayName: 'Clean Agent Directories'
+          condition: always()
 
   - ${{ if eq(parameters.msi_test, true) }}:
     - job: Set_7
@@ -1817,7 +2031,7 @@ jobs:
             sudo rm -rf $(TEMP_DIR)/*
           displayName: 'Clean Agent Directories'
           condition: always()
-    
+
   - ${{ if eq(parameters.proxy_test, true) }}:    
     - job: Set_8
       timeoutInMinutes: 60
