Vibhansa/msi pipeline adls (#549)
- Corrected description for blobEndpoint in Readme
- MSI auth test case addition for both block blob and adls in nightly pipeline
- In case of RHEL/CentOS 7 where auth is done in background, no error was shown on console in case of failure. Now blobfuse will display auth failure error on console and unmount itself if authentication fails.

diff --git a/blobfuse-nightly.yml b/blobfuse-nightly.yml
--- a/blobfuse-nightly.yml
+++ b/blobfuse-nightly.yml
@@ -705,7 +705,7 @@ jobs:
   - ${{ if eq(parameters.exhaustive_test, true) }}:
     # Other then Ubuntu just run the feature_test
     - job: Set_2
-      timeoutInMinutes: 240
+      timeoutInMinutes: 30
       strategy:
         matrix:
           RHEL-7.5-new-curl:
@@ -867,6 +867,8 @@ jobs:
         - script:  |
             curl --version
             sudo fusermount -u $(MOUNT_DIR)
+            sudo kill -9 `pidof ./build/blobfuse`
+            sudo kill -9 `pidof fusermount`
             sudo rm -rf $(MOUNT_DIR)/*
             sudo rm -rf $(TEMP_DIR)/*
             ./build/blobfuse $(MOUNT_DIR) --tmp-path=$(TEMP_DIR) --config-file=$(BLOBFUSE_CFG_FILE) --file-cache-timeout-in-seconds=0 --use-adls=true --use-attr-cache=true
@@ -879,19 +881,49 @@ jobs:
             go test -v feature_test.go -args -mnt-path=$(MOUNT_DIR) -adls=true
           workingDirectory: $(ROOT_DIR)
           displayName: TEST - ADLS FeatureTest
-          timeoutInMinutes: 120
+          timeoutInMinutes: 20
 
         - script:  |
             rm -rf $(MOUNT_DIR)/*
             sudo fusermount -u $(MOUNT_DIR)
-            sudo kill -9 `pidof blobfuse`
+          workingDirectory: $(ROOT_DIR)
+          displayName: 'Unmount blobfuse'
+          timeoutInMinutes: 5
+          condition: always()
+
+        # --- Negative testing for auth failure post fork
+        - script: |
+            sudo touch $(BLOBFUSE_CFG_FILE)
+            sudo chown -R `whoami` $(BLOBFUSE_CFG_FILE)
+            chmod 777 $(BLOBFUSE_CFG_FILE)
+            echo "accountName " $(NIGHTLY_STO_ACC_NAME) > $(BLOBFUSE_CFG_FILE)
+            echo "accountKey " $(NIGHTLY_STO_ACC_KEY) "abc" >> $(BLOBFUSE_CFG_FILE)
+            echo "authType Key" >> $(BLOBFUSE_CFG_FILE)
+            echo "containerName " $(containerName) >> $(BLOBFUSE_CFG_FILE)
+            cat $(BLOBFUSE_CFG_FILE)
+            echo "Account : " $(NIGHTLY_STO_ACC_NAME)
+          displayName: "Create config file - Negative"
+          # condition: or(eq(variables.containerName, 'test-cnt-rhel-75-test'), eq(variables.containerName, 'test-cnt-rhel-82'))
+
+        # Mount a directory for feature test (Block) and run it
+        # This mount is bound to fail so to ignore the exit code of the blobfuse use '|| :' to redirect output to null
+        # with this output will come on screen but the piepline task will not fail due to exit(1) by blobfuse
+        - script:  |
+            ./build/blobfuse $(MOUNT_DIR) --tmp-path=$(TEMP_DIR) --config-file=$(BLOBFUSE_CFG_FILE) --file-cache-timeout-in-seconds=0 --use-adls=true --use-attr-cache=true 2>&1 || :
+          workingDirectory: $(ROOT_DIR)
+          displayName: "Mount Blobfuse - Negative"
+          # condition: or(eq(variables.containerName, 'test-cnt-rhel-75-test'), eq(variables.containerName, 'test-cnt-rhel-82'))
+
+        - script:  |
+            rm -rf $(MOUNT_DIR)/*
+            sudo fusermount -u $(MOUNT_DIR)
             sudo rm -rf $(TEMP_DIR)/
             sudo rm -rf $(MOUNT_DIR)
             sudo rm -rf $(BLOBFUSE_CFG_FILE)
             sudo rm -rf $(WORK_DIR)
           workingDirectory: $(ROOT_DIR)
           displayName: 'Cleanup Directories'
-          timeoutInMinutes: 30
+          timeoutInMinutes: 5
           condition: always()
 
         - script: |
@@ -902,7 +934,7 @@ jobs:
           condition: always()
 
     - job: Set_3
-      timeoutInMinutes: 240
+      timeoutInMinutes: 30
       strategy:
         matrix:
           Debian-9.0:
@@ -1045,7 +1077,7 @@ jobs:
             go test -v feature_test.go -args -mnt-path=$(MOUNT_DIR) -adls=true
           workingDirectory: $(ROOT_DIR)
           displayName: TEST - ADLS FeatureTest
-          timeoutInMinutes: 120
+          timeoutInMinutes: 20
 
         - script:  |
             sudo rm -rf $(MOUNT_DIR)/*
@@ -1057,7 +1089,7 @@ jobs:
             sudo rm -rf $(WORK_DIR)
           workingDirectory: $(ROOT_DIR)
           displayName: 'Cleanup Directories'
-          timeoutInMinutes: 30
+          timeoutInMinutes: 5
           condition: always()
 
         - script: |
@@ -1068,7 +1100,7 @@ jobs:
           condition: always()
 
     - job: Set_4
-      timeoutInMinutes: 240
+      timeoutInMinutes: 30
       strategy:
         matrix:
           SUSE-15G2:
@@ -1205,7 +1237,7 @@ jobs:
             go test -v feature_test.go -args -mnt-path=$(MOUNT_DIR) -adls=true
           workingDirectory: $(ROOT_DIR)
           displayName: TEST - ADLS FeatureTest
-          timeoutInMinutes: 120
+          timeoutInMinutes: 20
 
         - script:  |
             sudo rm -rf $(MOUNT_DIR)/*
@@ -1217,7 +1249,7 @@ jobs:
             sudo rm -rf $(WORK_DIR)
           workingDirectory: $(ROOT_DIR)
           displayName: 'Cleanup Directories'
-          timeoutInMinutes: 30
+          timeoutInMinutes: 5
           condition: always()
 
         - script: |
@@ -1230,7 +1262,7 @@ jobs:
 
   - ${{ if eq(parameters.msi_test, true) }}:
     - job: Set_5
-      timeoutInMinutes: 100
+      timeoutInMinutes: 30
       strategy:
         matrix:
           MSI_Test:
@@ -1363,7 +1395,7 @@ jobs:
             sudo kill -9 `pidof blobfuse`
           # condition: eq(variables['Build.SourceBranchName'], 'master')
           displayName: TEST - MSI Validation
-          timeoutInMinutes: 120
+          timeoutInMinutes: 20
           continueOnError: true
 
         - script: |
@@ -1376,4 +1408,174 @@ jobs:
           displayName: 'Clean Agent Directories'
           condition: always()
 
+  - ${{ if eq(parameters.msi_test, true) }}:
+    - job: Set_6
+      timeoutInMinutes: 60
+      strategy:
+        matrix:
+          MSI_Test:
+            DistroVer: "Ubn20_MSI"
+            AgentName : "MSITestUBN20"
+            Description: "MSI Test - 2"
+
+      pool:
+        name: "Blobfuse Pool"
+        demands:
+        - Agent.Name -equals $(AgentName)
+
+      variables:
+      - group: NightlyBlobFuse
+      - name: WORK_DIR
+        value: "/home/vsts/work/"
+      - name: ROOT_DIR
+        value: "/home/vsts/work/azure-storage-fuse"
+      - name: skipComponentGovernanceDetection
+        value: true
+
+      - name: MOUNT_DIR
+        value: "/home/vibhansa/blob_mnt"
+      - name: TEMP_DIR
+        value: "/mnt/blobfusetmp"
+      - name: BLOBFUSE_CFG_FILE
+        value: "/home/vibhansa/myblob.cfg.msi"
+      - name: BLOBFUSE_CFG_FILE_ADLS
+        value: "/home/vibhansa/myblob.cfg.msi.adls"
+      
+      steps:
+        - checkout: none
+
+        # Install all dependencies
+        - script: |
+            echo $(Description)
+            hostnamectl
+          displayName: "Print Agent Info"
+
+        # Install all dependencies
+        - script: |
+            sudo apt-get update --fix-missing
+            sudo apt-get install pkg-config cmake libcurl4-gnutls-dev libgnutls28-dev uuid-dev libgcrypt20-dev libboost-all-dev gcc g++ golang -y
+          displayName: "Basic Tools Setup"
+
+        # Install libfuse
+        - script: |
+            sudo apt-get install libfuse-dev fuse -y
+          displayName: "libFuse Setup"
+
+        # Prebuild cleanup
+        - script: |
+            sudo fusermount -u $(MOUNT_DIR)
+            sudo kill -9 `pidof blobfuse`
+            sudo rm -rf $(WORK_DIR)
+          displayName: "Prebuild cleanup"
+
+        # Checkout code
+        - script: |
+            sudo mkdir -p $(WORK_DIR)
+            sudo chown -R `whoami` $(WORK_DIR)
+            chmod 777 $(WORK_DIR)
+          displayName: "Create Directory structure"
+
+        # Checkout code
+        - script: |
+            git clone https://github.com/Azure/azure-storage-fuse
+          displayName: "Checkout code"
+          workingDirectory: $(WORK_DIR)
+
+        # Checkout branch
+        - script: |
+            echo $(Build.SourceBranch)
+            echo "Going for checkout of " `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`  
+            git checkout `echo $(Build.SourceBranch) | cut -d "/" -f 1,2 --complement`   
+          displayName: "Checkout Branch"
+          workingDirectory: $(ROOT_DIR)
+
+        # List commits consumed for this build
+        - script: |
+            echo "Below commits were done in last 12 hours : " `date` 
+            git --no-pager log --since="12 hours ago" --stat
+          displayName: "List Commits"
+          workingDirectory: $(ROOT_DIR)
+
+        # Build the blobFuse binary
+        - script: |
+            sudo chmod +x build.sh
+            . ./build.sh
+          displayName: "Build BlobFuse"
+          workingDirectory: $(ROOT_DIR)
+
+        # Test the binary just to make sure it was built fine
+        - script: |
+            ./build/blobfuse --version
+          displayName: "Test the binary"
+          workingDirectory: $(ROOT_DIR)
+
+        # Add the test work here
+        # Create directory structures for the basic testing
+        - script: |
+            sudo mkdir $(MOUNT_DIR)
+            sudo chown -R `whoami` $(MOUNT_DIR)
+            chmod 777 $(MOUNT_DIR)
+            sudo mkdir $(TEMP_DIR)
+            sudo chown -R `whoami` $(TEMP_DIR)
+            chmod 777 $(TEMP_DIR)
+          displayName: "Create Directories"
+        
+        # Mount a directory for feature test (Block) and run it
+        - script:  |
+            curl --version
+            sudo fusermount -u $(MOUNT_DIR)
+            sudo rm -rf $(MOUNT_DIR)/*
+            sudo rm -rf $(TEMP_DIR)/*
+            ./build/blobfuse $(MOUNT_DIR) --tmp-path=$(TEMP_DIR) --config-file=$(BLOBFUSE_CFG_FILE)
+          workingDirectory: $(ROOT_DIR)
+          displayName: "Mount Blobfuse"
+
+        # List the blobs to verify that the login went successful
+        - script:  |
+            df
+            sudo ps -aux | grep blobfuse
+            ls -l $(MOUNT_DIR)
+            mkdir $(MOUNT_DIR)/MSITest
+            touch $(MOUNT_DIR)/MSITest/b.txt
+            echo "ASDF" > $(MOUNT_DIR)/MSITest/c.txt
+            cp $(MOUNT_DIR)/MSITest/c.txt $(MOUNT_DIR)/MSITest/d.txt
+            ls -lRt $(MOUNT_DIR)/MSITest
+            rm -rf $(MOUNT_DIR)/MSITest
+            sudo fusermount -u $(MOUNT_DIR)
+          # condition: eq(variables['Build.SourceBranchName'], 'master')
+          displayName: TEST - MSI Validation
+          timeoutInMinutes: 20
+          continueOnError: true
+          workingDirectory: $(ROOT_DIR)
+
+        # List the blobs to verify that the login went successful
+        - script:  |
+            sudo fusermount -u $(MOUNT_DIR)
+            sudo rm -rf $(MOUNT_DIR)/*
+            sudo rm -rf $(TEMP_DIR)/*
+            ./build/blobfuse $(MOUNT_DIR) --tmp-path=$(TEMP_DIR) --config-file=$(BLOBFUSE_CFG_FILE_ADLS) --use-adls=true
+            df
+            sudo ps -aux | grep blobfuse
+            mkdir $(MOUNT_DIR)/MSITestADLS
+            touch $(MOUNT_DIR)/MSITestADLS/b.txt
+            echo "ASDF" > $(MOUNT_DIR)/MSITestADLS/c.txt
+            cp $(MOUNT_DIR)/MSITestADLS/c.txt $(MOUNT_DIR)/MSITestADLS/d.txt
+            ls -lRt $(MOUNT_DIR)/MSITestADLS
+            rm -rf $(MOUNT_DIR)/MSITestADLS
+            sudo fusermount -u $(MOUNT_DIR)
+          # condition: eq(variables['Build.SourceBranchName'], 'master')
+          displayName: TEST - MSI Validation ADLS
+          timeoutInMinutes: 20
+          continueOnError: true
+          workingDirectory: $(ROOT_DIR)
+
+        - script: |
+            pwd
+            cd /`pwd | cut -d '/' -f 2,3,4,5`
+            sudo rm -rf [0-9]
+            sudo rm -rf $(WORK_DIR)
+            sudo rm -rf $(MOUNT_DIR)/*
+            sudo rm -rf $(TEMP_DIR)/*
+          displayName: 'Clean Agent Directories'
+          condition: always()
     
