Update blobfuse_ci.yml

diff --git a/.github/workflows/blobfuse_ci.yml b/.github/workflows/blobfuse_ci.yml
--- a/.github/workflows/blobfuse_ci.yml
+++ b/.github/workflows/blobfuse_ci.yml
@@ -89,12 +89,21 @@ jobs:
     - name: Mount container
       run: |
         sudo ./build/blobfuse $MOUNT_DIR --tmp-path=$TEMP_DIR --container-name=$CONT_NAME -o allow_other --log-level=LOG_DEBUG
+        RES = $?
+        if [ $RES -eq 0]; then
+          echo "BlobFuse mounted sucessfully with ENV variables"
+        else
+          echo "BlobFuse mount with ENV failed, retrying with config file"
+          sudo ./build/blobfuse $MOUNT_DIR --tmp-path=$TEMP_DIR --config-file=$BLOBFUSE_CFG --container-name=$CONT_NAME -o allow_other --log-level=LOG_DEBUG
+          RES = $?
+          if [ $RES -eq 0]; then
+            echo "BlobFuse mount succeded with config file"
+          else
+            echo "Failed to mount with config file as well"
+          fi
+        fi
         
-   # Check mount when fine or not, if not retry with config file
-    - name: Retry with config file if mount failed
-       if ${{ !SUCCESS }}
-         sudo ./build/blobfuse $MOUNT_DIR --tmp-path=$TEMP_DIR --config-file=$BLOBFUSE_CFG --container-name=$CONT_NAME -o allow_other --log-level=LOG_DEBUG
-      
+        
    # Check the mount went through or not by listing the mounted directory
     - name: Check directory listing
       run: ls -l $MOUNT_DIR
